apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.name" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "app.name" . }}
  replicas: 0
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "app.name" . }}
    spec:
      serviceAccountName: {{ template "app.name" . }}
      terminationGracePeriodSeconds: 30
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          name: {{ template "app.name" . }}
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5

---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ template "app.name" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "app.name" . }}
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 600
  progressDeadlineAbort: true
  rollbackWindow:
    revisions: 3
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "app.name" . }}
  strategy:
    blueGreen:
      activeService: {{ template "app.name" . }}
      previewService: {{ template "app.name" . }}-preview
      autoPromotionEnabled: false
