apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.name" . }}
spec:
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ template "app.name" . }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.name" . }}-preview
spec:
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ template "app.name" . }}
